<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="RIPUN_NOOB-Dev" failures="2" tests="10" name="Functional Tests" time="47.787" errors="0" timestamp="2024-12-14T02:57:00 IST">
  <testcase classname="com.jobbox.AppTest" name="testWebsiteAccessibility" time="1.54"/>
  <testcase classname="com.jobbox.AppTest" name="testWebsiteLoading" time="1.47"/>
  <testcase classname="com.jobbox.NavigationTest" name="testNavigationItemClickability" time="7.084"/>
  <testcase classname="com.jobbox.NavigationTest" name="testNavigationMenuItems" time="2.63"/>
  <testcase classname="com.jobbox.NavigationTest" name="testNavigationMenuItemsTwo" time="2.545">
    <failure type="java.lang.AssertionError" message="Navigation item &amp;apos;navitem&amp;apos; not found expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Navigation item 'navitem' not found expected [true] but found [false]
at com.jobbox.NavigationTest.lambda$testNavigationMenuItemsTwo$6(NavigationTest.java:148)
at java.base/java.lang.Iterable.forEach(Iterable.java:75)
at com.jobbox.NavigationTest.testNavigationMenuItemsTwo(NavigationTest.java:148)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- testNavigationMenuItemsTwo -->
  <testcase classname="com.jobbox.LoginTest" name="aatestLoginFromHomePage" time="4.406"/>
  <testcase classname="com.jobbox.LoginTest" name="atestInvalidoneLoginFromHomePage" time="4.618"/>
  <testcase classname="com.jobbox.LoginTest" name="btestInvalidtwoLoginFromHomePage" time="4.389"/>
  <testcase classname="com.jobbox.LoginTest" name="ctestInvalidLoginFromHomePage" time="5.904"/>
  <testcase classname="com.jobbox.DropdownTest" name="testDropdownMenuOnClick" time="3.134">
    <failure type="java.lang.AssertionError" message="Navigation failed for dropdown item: Employer did not expect [https://jobbox-gules.vercel.app/] but found [https://jobbox-gules.vercel.app/]">
      <![CDATA[java.lang.AssertionError: Navigation failed for dropdown item: Employer did not expect [https://jobbox-gules.vercel.app/] but found [https://jobbox-gules.vercel.app/]
at com.jobbox.DropdownTest.testDropdownMenuOnClick(DropdownTest.java:72)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- testDropdownMenuOnClick -->
</testsuite> <!-- Functional Tests -->
